#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_fizz_buzz:
    path: /1
    controller: App\Controller\TopController::fizzBuzz

app_reverse:
    path: /2
    controller: App\Controller\TopController::reverse

app_password:
    path: /3
    controller: App\Controller\TopController::password

app_password_reset:
    path: /3/{username}
    controller: App\Controller\TopController::resetPassword

app_rotate:
    path: /4/{direction}/{array}
    controller: App\Controller\TopController::rotate
